title: "System Friction"
description: "Archivo de fricción sistémica · v1.1 · 2026"
url: "https://systemfriction.org"
baseurl: ""
author: "Juan Antonio Marín Liera"
email: "aptymok@gmail.com"
version: "1.1"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  docs:
    output: true
    permalink: /docs/:name/
  nodo_ags:
    output: true
    permalink: /nodo-ags/:name/
  mihm:
    output: true
    permalink: /mihm/:name/

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
      version: "1.1"
      status: "validated"
  - scope:
      path: ""
      type: "nodo_ags"
    values:
      layout: "doc"
  - scope:
      path: ""
      type: "mihm"
    values:
      layout: "doc"